[build]
  command = "yarn run build"
  publish = "_site"

[context.production]
  command = "yarn run build"

  [context.production.environment]
    ELEVENTY_ENV = "production"
    NETLIFY_USE_YARN = "true"
    NODE_ENV = "production"
    NODE_VERSION = "18"
    TZ = "Europe/Sofia"

[[headers]]
  for = "/*"

  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    Referrer-Policy= "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.json"

  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/*.webmanifest"

  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

# Netlify subdomain
[[redirects]]
  from = "https://elvenbrill.netlify.app/*"
  to = "https://elvenbrill.xyz/:splat"
  status = 301
  force = true

# www subdomain
[[redirects]]
  from = "https://www.elvenbrill.xyz/*"
  to = "https://elvenbrill.xyz/:splat"
  status = 301
  force = true

# 404s
[[redirects]]
  from = "*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/favicon.ico"
  to = "/assets/icons/favicon.ico"
  status = 200
  force = true

[[redirects]]
  from = "/articles/*"
  to = "/notes/:splat"
  status = 301
  force = true
